In [1]:
import pandas as pd
import numpy as np

In [3]:
# Load Adult dataset
dataset = pd.read_csv("../dataset/adult.data.txt",
    names=["Age", "Workclass", "fnlwgt", "Education", "Education-Num", "Martial Status",
        "Occupation", "Relationship", "Race", "Sex", "Capital Gain", "Capital Loss",
        "Hours per week", "Country", "Target"],sep=r'\s*,\s*',na_values="?",engine='python')
dataset.tail()

,Age,Workclass,fnlwgt,Education,Education-Num,Martial Status,Occupation,Relationship,Race,Sex,Capital Gain,Capital Loss,Hours per week,Country,Target
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [4]:
#Find actual data count
datacount = dataset["Country"].value_counts()
print("datacount: \n", datacount)

datacount:
 United-States                 29170
Mexico                          643
Philippines                     198
Germany                         137
Canada                          121
Puerto-Rico                     114
El-Salvador                     106
India                           100
Cuba                             95
England                          90
Jamaica                          81
South                            80
China                            75
Italy                            73
Dominican-Republic               70
Vietnam                          67
Guatemala                        64
Japan                            62
Poland                           60
Columbia                         59
Taiwan                           51
Haiti                            44
Iran                             43
Portugal                         37
Nicaragua                        34
Peru                             31
Greece                           29
France                           29
Ecuador                          28
Ireland                          24
Hong                             20
Cambodia                         19
Trinadad&Tobago                  19
Laos                             18
Thailand                         18
Yugoslavia                       16
Outlying-US(Guam-USVI-etc)       14
Honduras                         13
Hungary                          13
Scotland                         12
Holand-Netherlands                1
Name: Country, dtype: int64

In [5]:
# Get index of datacount, "Country"
index = list(datacount.index)
# Get value of datacount, "number each Country"
number = list(datacount.values)

In [6]:
# Set parameters for Exponential function implementation
# L1 Sentivity = 1
# Epsilon =  0, 0.01, 0.05
eps = [0.0, 0.01, 0.05]
sensitivity = 1.0

In [8]:
for i in range(3):
    print("epsilon = " + str(eps[i]) + "\n")
    # Calculate Score with Exponential Mechanism
    score = np.exp(eps[i] * datacount / (2 * sensitivity))
    print("score: \n", score)
    print("------------------------------------------")

    # Calculate probablity of each country
    sum_score = score.sum()
    probablity = score / sum_score
    print("\nprobablity: \n", probablity)
    print("------------------------------------------")

epsilon = 0.0

score:
 United-States                 1.0
Mexico                        1.0
Philippines                   1.0
Germany                       1.0
Canada                        1.0
Puerto-Rico                   1.0
El-Salvador                   1.0
India                         1.0
Cuba                          1.0
England                       1.0
Jamaica                       1.0
South                         1.0
China                         1.0
Italy                         1.0
Dominican-Republic            1.0
Vietnam                       1.0
Guatemala                     1.0
Japan                         1.0
Poland                        1.0
Columbia                      1.0
Taiwan                        1.0
Haiti                         1.0
Iran                          1.0
Portugal                      1.0
Nicaragua                     1.0
Peru                          1.0
Greece                        1.0
France                        1.0
Ecuador                       1.0
Ireland                       1.0
Hong                          1.0
Cambodia                      1.0
Trinadad&Tobago               1.0
Laos                          1.0
Thailand                      1.0
Yugoslavia                    1.0
Outlying-US(Guam-USVI-etc)    1.0
Honduras                      1.0
Hungary                       1.0
Scotland                      1.0
Holand-Netherlands            1.0
Name: Country, dtype: float64
------------------------------------------

probablity:
 United-States                 0.02439
Mexico                        0.02439
Philippines                   0.02439
Germany                       0.02439
Canada                        0.02439
Puerto-Rico                   0.02439
El-Salvador                   0.02439
India                         0.02439
Cuba                          0.02439
England                       0.02439
Jamaica                       0.02439
South                         0.02439
China                         0.02439
Italy                         0.02439
Dominican-Republic            0.02439
Vietnam                       0.02439
Guatemala                     0.02439
Japan                         0.02439
Poland                        0.02439
Columbia                      0.02439
Taiwan                        0.02439
Haiti                         0.02439
Iran                          0.02439
Portugal                      0.02439
Nicaragua                     0.02439
Peru                          0.02439
Greece                        0.02439
France                        0.02439
Ecuador                       0.02439
Ireland                       0.02439
Hong                          0.02439
Cambodia                      0.02439
Trinadad&Tobago               0.02439
Laos                          0.02439
Thailand                      0.02439
Yugoslavia                    0.02439
Outlying-US(Guam-USVI-etc)    0.02439
Honduras                      0.02439
Hungary                       0.02439
Scotland                      0.02439
Holand-Netherlands            0.02439
Name: Country, dtype: float64
------------------------------------------
epsilon = 0.01

score:
 United-States                 2.197102e+63
Mexico                        2.490329e+01
Philippines                   2.691234e+00
Germany                       1.983772e+00
Canada                        1.831252e+00
Puerto-Rico                   1.768267e+00
El-Salvador                   1.698932e+00
India                         1.648721e+00
Cuba                          1.608014e+00
England                       1.568312e+00
Jamaica                       1.499303e+00
South                         1.491825e+00
China                         1.454991e+00
Italy                         1.440514e+00
Dominican-Republic            1.419068e+00
Vietnam                       1.397940e+00
Guatemala                     1.377128e+00
Japan                         1.363425e+00
Poland                        1.349859e+00
Columbia                      1.343126e+00
Taiwan                        1.290462e+00
Haiti                         1.246077e+00
Iran                          1.239862e+00
Portugal                      1.203218e+00
Nicaragua                     1.185305e+00
Peru                          1.167658e+00
Greece                        1.156040e+00
France                        1.156040e+00
Ecuador                       1.150274e+00
Ireland                       1.127497e+00
Hong                          1.105171e+00
Cambodia                      1.099659e+00
Trinadad&Tobago               1.099659e+00
Laos                          1.094174e+00
Thailand                      1.094174e+00
Yugoslavia                    1.083287e+00
Outlying-US(Guam-USVI-etc)    1.072508e+00
Honduras                      1.067159e+00
Hungary                       1.067159e+00
Scotland                      1.061837e+00
Holand-Netherlands            1.005013e+00
Name: Country, dtype: float64
------------------------------------------

probablity:
 United-States                 1.000000e+00
Mexico                        1.133461e-62
Philippines                   1.224902e-63
Germany                       9.029039e-64
Canada                        8.334854e-64
Puerto-Rico                   8.048180e-64
El-Salvador                   7.732606e-64
India                         7.504073e-64
Cuba                          7.318797e-64
England                       7.138095e-64
Jamaica                       6.824001e-64
South                         6.789966e-64
China                         6.622321e-64
Italy                         6.556428e-64
Dominican-Republic            6.458816e-64
Vietnam                       6.362656e-64
Guatemala                     6.267929e-64
Japan                         6.205562e-64
Poland                        6.143815e-64
Columbia                      6.113173e-64
Taiwan                        5.873472e-64
Haiti                         5.671456e-64
Iran                          5.643170e-64
Portugal                      5.476389e-64
Nicaragua                     5.394856e-64
Peru                          5.314537e-64
Greece                        5.261657e-64
France                        5.261657e-64
Ecuador                       5.235414e-64
Ireland                       5.131746e-64
Hong                          5.030131e-64
Cambodia                      5.005043e-64
Trinadad&Tobago               5.005043e-64
Laos                          4.980080e-64
Thailand                      4.980080e-64
Yugoslavia                    4.930527e-64
Outlying-US(Guam-USVI-etc)    4.881468e-64
Honduras                      4.857121e-64
Hungary                       4.857121e-64
Scotland                      4.832896e-64
Holand-Netherlands            4.574265e-64
Name: Country, dtype: float64
------------------------------------------
epsilon = 0.05

score:
 United-States                          inf
Mexico                        9.578198e+06
Philippines                   1.411750e+02
Germany                       3.072264e+01
Canada                        2.059400e+01
Puerto-Rico                   1.728778e+01
El-Salvador                   1.415404e+01
India                         1.218249e+01
Cuba                          1.075101e+01
England                       9.487736e+00
Jamaica                       7.576111e+00
South                         7.389056e+00
China                         6.520819e+00
Italy                         6.202795e+00
Dominican-Republic            5.754603e+00
Vietnam                       5.338795e+00
Guatemala                     4.953032e+00
Japan                         4.711470e+00
Poland                        4.481689e+00
Columbia                      4.371036e+00
Taiwan                        3.578701e+00
Haiti                         3.004166e+00
Iran                          2.929993e+00
Portugal                      2.521868e+00
Nicaragua                     2.339647e+00
Peru                          2.170592e+00
Greece                        2.064731e+00
France                        2.064731e+00
Ecuador                       2.013753e+00
Ireland                       1.822119e+00
Hong                          1.648721e+00
Cambodia                      1.608014e+00
Trinadad&Tobago               1.608014e+00
Laos                          1.568312e+00
Thailand                      1.568312e+00
Yugoslavia                    1.491825e+00
Outlying-US(Guam-USVI-etc)    1.419068e+00
Honduras                      1.384031e+00
Hungary                       1.384031e+00
Scotland                      1.349859e+00
Holand-Netherlands            1.025315e+00
Name: Country, dtype: float64
------------------------------------------

probablity:
 United-States                 NaN
Mexico                        0.0
Philippines                   0.0
Germany                       0.0
Canada                        0.0
Puerto-Rico                   0.0
El-Salvador                   0.0
India                         0.0
Cuba                          0.0
England                       0.0
Jamaica                       0.0
South                         0.0
China                         0.0
Italy                         0.0
Dominican-Republic            0.0
Vietnam                       0.0
Guatemala                     0.0
Japan                         0.0
Poland                        0.0
Columbia                      0.0
Taiwan                        0.0
Haiti                         0.0
Iran                          0.0
Portugal                      0.0
Nicaragua                     0.0
Peru                          0.0
Greece                        0.0
France                        0.0
Ecuador                       0.0
Ireland                       0.0
Hong                          0.0
Cambodia                      0.0
Trinadad&Tobago               0.0
Laos                          0.0
Thailand                      0.0
Yugoslavia                    0.0
Outlying-US(Guam-USVI-etc)    0.0
Honduras                      0.0
Hungary                       0.0
Scotland                      0.0
Holand-Netherlands            0.0
Name: Country, dtype: float64
------------------------------------------